### ISSUE TITLE
Page for viewing images

### ISSUE THREAD

**Issue by philipperker** [philipperker/capstone-project#1]
## Value statement - a requirement, not a solution
As a user
I need a list for pictures. So that I can look at different NFT collections

## Description (Text, Scribble, Wireframe, Design)
![grafik](https://user-images.githubusercontent.com/100590544/166140758-5fe8fb1b-0343-48de-a584-9f5bec596b9b.png)

The NFT collections are aligned vertically. The user can scroll horizontally in each collections to see more images.
## Acceptance criteria
- [x] Page should show three NFT collection
- [x] Scroll horizontally for more images (Do not use a carousel effect for horizontal scrolling)
- [x] Only eight images should be displayed from each collection.
- [x] Background color #741DF6

## Tasks
- [x] install storybook
- [x] Create the card components for the NFT collection
- [x] Create a test NFT collection
- [x] Fetch the data "image" from https://capstone-test-api.vercel.app/
- [ ] Testing 
- [x] Deploy for usability and UX testing

## Size
 medium

**Comment by PReichetanz** [comment]
I think that this is a good starting point!

Just one thing to think about:
- The value proposition is not complete, there is missing the "in order to" part even if it might seem redundant. Additionally, the second sentence belongs to acceptance criteria.

One could go in more detail in regards to tasks, but it's fine as long as you know what to do.

**Comment by philipperker** [comment]
Thanks you for your feedback :) I will revise the user-story again!
