### ISSUE TITLE
Detail card NFT images 

### ISSUE THREAD

**Issue by philipperker** [philipperker/capstone-project#3]
## Value statement - a requirement, not a solution
As a user
I need a way to get information about individual NFT. So that I can evaluate the NFT.

## Description (Text, Scribble, Wireframe, Design)
![grafik](https://user-images.githubusercontent.com/100590544/167376055-1f3fab8d-8287-458c-99f1-cd3b81f65409.png)

## Acceptance criteria
- [x] The detail card is intended to display information about the NFT
- [ ] The button gets a double function. Home button and to close the detail card.
- [x] The fake data should be displayed in the detail card

## Tasks
- [x] Create a detail card
- [x] Create a navbar with one button. 
- [x] Create a button
- [x] Fetch fake Data 
- [ ] Testing
- [x] Deploy for usability and UX testing

## Size
small

**Comment by philipperker** [comment]
Hi Mareike, thanks for your feedback :) I will revise the value statement in the user story again;)
