### ISSUE TITLE
Add new NFT

### ISSUE THREAD

**Issue by philipperker** [philipperker/capstone-project#4]
## Value statement - a requirement, not a solution
As a User
I need the ability to add more NFT. When I add new NFT I want them to be presented in a list.

## Description (Text, Scribble, Wireframe, Design)
![grafik](https://user-images.githubusercontent.com/100590544/167389358-35b7db47-14f6-4d58-8d1d-e266ece588fd.png)
*The icons for the buttons are added in the finallen design
## Acceptance criteria
- [ ] The metadata of the newly added NFT should be stored in a database.
- [ ] The newly added NFT should be displayed on the Add NFT page and on the Home page.

## Tasks
- [ ] Create a second button in Navbar
- [ ] Create a page called "add NFT"
- [ ] Create an add button
- [ ] Create an input field
- [ ] Create a database

## Size
 large

**Comment by mbosselmann** [comment]
Hi Philipp, I also like this user story! 👍 I have some remarks:

- The **value statement** is also missing the reason for this feature (see my remark for your 3rd user story).
- Your **acceptance criteria** are missing that there should be a form where the user can enter the data and also that the user can see in the navbar on which page the person is
- The **first point of your acceptance criteria** is a task and not an acceptance criterion
- And about the **task "Create a database"**: Do you also want to implement the backend while working on this user story? As this is a large task that is not necessary for this feature, I would recommend you to separate the database task in an own user story. You could also think about working with localStorage and implementing the backend later.

**Comment by philipperker** [comment]
Hi Mareike, thanks for the feedback. I will split this user story into two user stories;)
